name: build

env:
  BUILD_TYPE: Release

on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '14.2.Rel1' # <-- The compiler release to use

    - name: Install srec_cat
      run: sudo apt-get update && sudo apt-get install -y srecord

    - name : Create build directory
      run: mkdir -p build

    - name: build
      working-directory: ./build  
      run: |
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
        make -j4

    - name: Download Artifacts HEX
      uses: actions/upload-artifact@v4
      with:
        name: "Download artifacts - HEX"
        path: build/*.hex

